import Solution from "./Solution";
import Selector from "./Selector";
import Population from "./Population";
import importer from "./importer";
import Counter from "./Counter";

// import menu from "./menu";
// import importer from "./importer";
// import Timer from "./timer";
// menu();
const nodes = importer("br17");
const array = [];
const counter = new Counter(nodes);
const populationMaker = new Population(200);
const population = populationMaker.makeRandomPopulation(nodes);
population.map(value => counter.count_value_of_solution(value));
console.log(population);
const selector = new Selector(10);
const newBest = selector.chooseTheBestSolutions(population);
console.log("finish", newBest);